server:
  port: 8088

Loggin:
  level:
    org.springframework : DEBUG

spring:
  messages:
    basename : messages
  security:
    user:
      name: username
      password: passw0rd

management:
  enpoints:
    web:
      exposure:
        include: "*"
